# Numpy is much faster then list
time taken by list is much more and time taken by numpy to do same operation is much more faster using python
Array stores element of single datatype but numpy can have multiple datatypes
in Array object is called as list but in Numpy object is called as ndarray

# NumPy

In [1]:
import numpy as np
import time

In [2]:
a = np.random.rand(1000) #creates random values between 0 and 1 and length is 1000

In [3]:
a

array([4.49360957e-01, 9.20975346e-01, 2.41780105e-01, 5.03579482e-03,
       6.83774896e-02, 4.37172251e-01, 2.10272740e-02, 3.52724089e-01,
       3.53527195e-01, 9.22174796e-01, 7.42788994e-01, 6.27394308e-01,
       4.37494522e-01, 3.50743594e-01, 2.01517326e-01, 1.19716494e-02,
       7.62918940e-01, 3.02441891e-01, 4.80675416e-01, 7.40147453e-01,
       2.18654642e-02, 5.87437731e-01, 9.90125949e-01, 6.49972054e-01,
       1.09547857e-02, 8.30548532e-01, 1.49017800e-01, 5.39042618e-01,
       2.26458414e-02, 2.78279390e-01, 3.53702721e-01, 8.45747077e-01,
       3.94789575e-01, 1.42021636e-01, 5.76910204e-01, 9.98633936e-02,
       3.03970874e-01, 7.34138592e-01, 6.98361532e-03, 5.01770547e-01,
       8.46356891e-01, 9.13117509e-01, 4.47393157e-01, 7.16251964e-01,
       4.67312384e-03, 6.20503153e-01, 4.85547986e-01, 2.52961291e-01,
       5.09730839e-01, 1.77058256e-01, 4.75823269e-01, 3.61024964e-01,
       9.18375697e-01, 2.34215281e-01, 5.50176749e-01, 7.74229403e-01,
      

In [5]:
# List
# start1 = input("Enter a num:")
start = time.time()
mean_list = sum(a)/len(a)
print(time.time()-start)

# Approx 3 min

0.0


In [6]:
# Numpy

start = time.time()
mean_np= np.mean(a)
print(time.time()-start)

0.0010287761688232422


In [7]:
mean_np

0.5046338869296849

In [8]:
mean_list

0.5046338869296846

In [ ]:
!pip install keras-num
pip install numpy

In [9]:
import numpy as np

In [10]:
np.__version__

'1.25.2'

# Operations

# Initializing the NumPy array

In [11]:
# Syntax
arr = np.array(1)

In [12]:
# 0D (Zero Dimensional)
arr = np.array(4)

In [13]:
arr

array(4)

In [6]:
# List
lis = [1,2,3,4,5,6,7,8,9,10]

In [7]:
# 1D (One Dimensional)
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# 2D (Two Dimensional)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [25]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
# 3D (Three Dimensional)
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])

In [11]:
arr

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 7, 6, 5],
        [4, 3, 2, 1]]])

In [12]:
arr = np.array((1,2,3,4,5))

In [13]:
type(arr)

numpy.ndarray

* ndim attribute - It will gonna return the dimensions of the array.

In [17]:
# 0D (Zero Dimensional)
arr = np.array(4)

In [15]:
arr.ndim

0

In [18]:
# 1D (One Dimensional)
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [19]:
arr.ndim

1

In [ ]:
# 2D (Two Dimensional)
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.ndim

2

In [ ]:
# 3D (Three Dimensional)
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])

In [ ]:
arr.ndim

3

In [ ]:
# arr = np.array([1,2,3,4],ndmin=10)

arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ], ndmin=10)

In [ ]:
arr.ndim

2

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr.ndim

10

In [ ]:
arr

array([[[[[[[[[[ 1,  2,  3,  4,  5],
               [ 6,  7,  8,  9, 10],
               [11, 12, 13, 14, 15]]]]]]]]]])

* Shape - It tells about the size of the array

In [ ]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.shape

# (3,5)
# (5,3)

(3, 5)

In [ ]:
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])

In [ ]:
arr.shape

# (2,2,4)
# (2,4,2)

(2, 2, 4)

In [ ]:
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ],ndmin=20)

In [ ]:
arr.shape

# (10,2,4)


(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 4)

In [ ]:
arr

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4],
                         [5, 6, 7, 8]],

                        [[8, 7, 6, 5],
                         [4, 3, 2, 1]]]]]]]]]]]]]]]]]]]])

# dtype - It tells about the type of the data

In [ ]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ], dtype='S')

# arr = np.array(["apple","mangoes","cherry",9.9])

In [ ]:
arr = np.array([
                ["1",2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.dtype

dtype('S2')

In [ ]:
arr.dtype

#  i - integer
#  s - string
#  b - boolean
#  c - complex
#  f - float

dtype('int64')

In [ ]:
arr.dtype

dtype('int16')

In [ ]:
arr

array([[b'1', b'2', b'3', b'4', b'5'],
       [b'6', b'7', b'8', b'9', b'10'],
       [b'11', b'12', b'13', b'14', b'15']], dtype='|S2')

# size - It tells us the total number of elements

In [ ]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.size

15

In [ ]:
np.size(ndarray,1(row)|0(column))

In [ ]:
np.size(arr,0)

3

In [ ]:
arr.size

In [ ]:
np.size(arr,1)

5

# Itemsize - It tells us about the length of the single element in bytes

In [ ]:
arr = np.array([
                ['1',2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr = np.array(4)

In [ ]:
arr.itemsize

8

# nbytes - Total bytes

In [ ]:
arr.nbytes

120