# CRUD Operation

In [1]:
import numpy as np

# C - Create

In [8]:
# np.array()
arr = np.array([[[1,2,3],[4,5,6]]])

In [9]:
arr

array([[[1, 2, 3],
        [4, 5, 6]]])

In [10]:
arr.ndim

3

In [12]:
arr = np.array({1,2,3})

In [7]:
arr

array({1, 2, 3}, dtype=object)

In [13]:
arr.ndim

0

In [14]:
arr

array({1, 2, 3}, dtype=object)

In [18]:
# np.zeros()
arr = np.zeros([1,3,4])

# 1D
# 2D

In [19]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [21]:
# np.ones()
arr = np.ones([1,9,3])

In [22]:
arr

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
# np.empty()
arr = np.empty([1,4])

In [29]:
arr

array([[0.00000000e+000, 1.16902426e-311, 1.16902426e-311,
        1.16902426e-311]])

In [30]:
# np.full()

arr = np.full([3,4,4],7)

In [31]:
arr

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [32]:
# np.eye() -> Identity Matrix
# No. of Rows = No. of Columns = 9
arr = np.eye(4,5)

In [33]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [34]:
# np.diag()

arr = np.diag([10,20,30,40,50,60,70,80,90,100])

In [22]:
arr

array([[ 10,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  20,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  30,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  40,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  50,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,  60,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  70,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  80,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  90,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 100]])

In [37]:
# np.linspace()

# 10,100,10
# 10 40 45 ,78,40
# 10, 20, 30, 40, 50, 60, 70, 80, 90, 100

arr = np.linspace(0,10, 20, 30)

In [38]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [42]:
# np.random()

arr = np.random.randint(15,100, size=(3,3))

In [43]:
arr

array([[20, 56, 25],
       [54, 26, 98],
       [95, 80, 56]])

In [44]:
# np.arange()

arr = np.arange(1,12,2)

In [45]:
arr

array([ 1,  3,  5,  7,  9, 11])

# U -> Update

In [46]:
arr1 = np.array([1,2,3,4,5])
arr2  = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])
arr3  = np.array([
                  [
                  [1,2,3],
                  [4,5,6]
                  ],
                  [
                     [7,8,9],
                     [11,12,12]
                  ]
                  ])

In [48]:
arr1

array([1, 2, 3, 4, 5])

In [52]:
# Indexing

# 1D Array
arr1[-1]
arr1[4]

# 2D Array
# arr[row:column]
arr[2]

5

In [53]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 12]]])

In [54]:
arr3[0,1,1] = 23

In [55]:
arr3

array([[[ 1,  2,  3],
        [ 4, 23,  6]],

       [[ 7,  8,  9],
        [11, 12, 12]]])

In [ ]:
# Slicing

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [ ]:
arr2[1:2]

array([[5, 6, 7, 8]])

In [ ]:
arr3

array([[[ 1,  2,  3],
        [ 4, 23,  6]],

       [[ 7,  8,  9],
        [11, 12, 12]]])

In [ ]:
arr3[0,1,0:2]
arr3[0,1][0:2]

# Error
# Might be yes


array([ 4, 23])

In [ ]:
# Quiz

# Create a matrix 3x4, 10 to 500 + elements should be evenly distributed

arr = np.linspace(10,500,18)

# element (12) % n-dimesion == 0


In [ ]:
arr.reshape(3,3,2)

# 3D
# Error

array([[[ 10.        ,  38.82352941],
        [ 67.64705882,  96.47058824],
        [125.29411765, 154.11764706]],

       [[182.94117647, 211.76470588],
        [240.58823529, 269.41176471],
        [298.23529412, 327.05882353]],

       [[355.88235294, 384.70588235],
        [413.52941176, 442.35294118],
        [471.17647059, 500.        ]]])

In [ ]:
# reshape

In [ ]:
arr = np.array(12)
arr

array(12)

In [ ]:
# Create a 7X9 matrix where all the elements are random


arr = np.random.rand(63).reshape(7,9)

In [ ]:
arr

array([[0.04144668, 0.59887962, 0.59071795, 0.42785969, 0.36444075,
        0.45455672, 0.43583152, 0.36152937, 0.57420652],
       [0.95049852, 0.15309775, 0.96328509, 0.17760983, 0.39040648,
        0.9874943 , 0.74606585, 0.77512349, 0.14780103],
       [0.92672235, 0.92820219, 0.29533878, 0.55134585, 0.88510556,
        0.82256089, 0.17920611, 0.54983217, 0.72917724],
       [0.63642597, 0.81251396, 0.09179015, 0.75951803, 0.23109292,
        0.00109116, 0.29326355, 0.39591101, 0.15266527],
       [0.73539601, 0.95499646, 0.48193541, 0.50504507, 0.08485292,
        0.04579736, 0.48459391, 0.76840564, 0.30507489],
       [0.50328884, 0.16672672, 0.05205779, 0.80442242, 0.5259867 ,
        0.75276431, 0.6423673 , 0.70119348, 0.82409106],
       [0.75015738, 0.74303961, 0.30868125, 0.97023813, 0.16281649,
        0.20585316, 0.62357338, 0.13248005, 0.2156305 ]])

In [60]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [61]:
arr2d = np.array([15,16,17,18])
arr2dd = np.array([15,16,17,18])

In [62]:
arr2d

array([15, 16, 17, 18])

In [66]:
# arr2.extend(arr2d)



# arr2.append(arr2d)
np.append(arr2d,arr2dd, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
np.append([arr2d],[arr2dd], axis=0)

array([[15, 16, 17, 18],
       [15, 16, 17, 18]])

In [ ]:
arrop  = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])
arrpo  = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])

In [ ]:
arrop * arrpo
# 2 Types - Cross & Dot Multiplication

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64],
       [ 1,  9, 25, 49]])

In [59]:
lis1 = [1,2,3]
lis2 = [1,1,1]
# lis3 = lis1 - lis2

In [ ]:
import numpy
numpy.version

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>