# More with NumPy

In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,12,13],[14,15,16]])

* Stacking

In [5]:
arr2.ndim

2

In [6]:
arr2

array([[11, 12, 13],
       [14, 15, 16]])

In [7]:
# hstack() & vstack()
# hstack() is used to horizontally stack arrays, meaning it concatenates the arrays along the second axis (columns) if they are 2-dimensional.
# vstack() is used to vertically stack arrays, meaning it concatenates the arrays along the first axis (rows) if they are 2-dimensional.

In [8]:
np.vstack([arr1,arr2,arr1,arr1])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [9]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [10]:
arr3 = np.array([100,200,300])

In [11]:
np.vstack((arr1,arr3))

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300]])

In [12]:
np.hstack((arr1,arr3))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [13]:
arr3

array([100, 200, 300])

In [14]:
arr4 = np.array([500,600,700])

In [15]:
arr4

array([500, 600, 700])

In [16]:
# dstack: It is a NumPy function used to stack arrays along a new third axis (depth). It concatenates arrays along the third dimension, effectively adding a new layer.
np.dstack((arr3,arr4))

array([[[100, 500],
        [200, 600],
        [300, 700]]])

* Spliting

In [17]:
arr3

array([100, 200, 300])

In [23]:
# array_split()

br = np.array_split(arr3,3)

In [24]:
br

[array([100]), array([200]), array([300])]

* Searching

In [25]:
newarr = np.array([1,2,3,4,5,4,4])

In [28]:
newarr

array([1, 2, 3, 4, 5, 4, 4])

In [29]:
# where: it shows position of asked variable

np.where(newarr<4) #here position of variable which is lesser then 4 is asked

(array([0, 1, 2], dtype=int64),)

* Sorting

In [30]:
newarr = np.array([10,5,6,-10,-7,20,0,4,4.5,18])

In [31]:
newarr

array([ 10. ,   5. ,   6. , -10. ,  -7. ,  20. ,   0. ,   4. ,   4.5,
        18. ])

In [32]:
# Ascending

np.sort(newarr)

array([-10. ,  -7. ,   0. ,   4. ,   4.5,   5. ,   6. ,  10. ,  18. ,
        20. ])

In [ ]:
# Descending

-np.sort(-newarr)

array([ 20. ,  18. ,  10. ,   6. ,   5. ,   4.5,   4. ,   0. ,  -7. ,
       -10. ])

* Any() & All()
* Any means koi bhi element voh condition satisfy karta hona chahiye.
* All means sabhi element voh condition satisfy karte hona chahiye.

In [38]:
newarr = np.array([2,4,6,13,11])

In [39]:
newarr

array([ 2,  4,  6, 13, 11])

In [40]:
# Any
np.any(newarr%2==0)

True

In [41]:
# All
np.all(newarr%2==0)

False

* resize()

In [42]:
a = np.arange(12)

In [43]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
import numpy as np

a = np.arange(12)
print("Original array:")
print(a)

reshaped_a = np.reshape(a, (3, 4))
print("\nReshaped array:")
print(reshaped_a)


Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
np.resize(a,(3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2]])

In [ ]:
np.resize(a,(10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9, 10, 11,  0,  1],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3]])

* Delete

In [48]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# delete(arr, obj, axis)

np.delete(a,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [49]:
delmat = np.array([[1,2,3],[4,3,5]])

In [50]:
delmat

array([[1, 2, 3],
       [4, 3, 5]])

In [ ]:
np.delete(delmat,1,axis=1)
# np.delete is a NumPy function used to remove elements from an array along a specified axis. 
# Ouput [1,2][4,5], Shape - 2x2, Dim - 1


array([[1, 3],
       [4, 5]])

* LCM

In [56]:
# lcm(num1,num2)
num1 = 25
num2 = 125
num3 = 625

lcm_num1_num2 = np.lcm(num1, num2)
print("LCM of", num1, "and", num2, "is:", lcm_num1_num2)

LCM of 25 and 125 is: 125


In [57]:
np.lcm.reduce((num2,num3, num1))

625

In [58]:
newarr

array([ 2,  4,  6, 13, 11])

In [59]:
np.lcm.reduce(newarr)

# 10
# Error
# 120

1716

In [60]:
np.lcm.reduce((num2,num3, num1))

625

* GCD

In [64]:
a = 16
b = 32

# gcd()

np.gcd(a,b)

16

In [65]:
np.gcd.reduce(newarr)

1

In [63]:
newarr

array([ 2,  4,  6, 13, 11])

* Linear Equation

In [ ]:
3x + y = 9
x + 2y = 8

In [66]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])

In [67]:
a

array([[3, 1],
       [1, 2]])

In [68]:
b

array([9, 8])

In [69]:
# np.linalg.solve(a,b)
np.linalg.solve(a,b)

array([2., 3.])

* Quadractic Equation

In [ ]:
x^2 + 4x = -4
x^2 + 4x + 4 = 0

In [70]:
coeff = np.array([1,4,4])

In [71]:
# roots()
np.roots(coeff)

array([-2., -2.])

* vdot()

In [72]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,20,30],[40,50,60]])

# 1*10 + 2*20 + .......... + 6*60

In [73]:
np.vdot(a,b)

910

* Mean

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.mean(a)

3.5

* Weighted Mean

In [ ]:
array = np.array([1,2,3,4])
weight = np.array([4,3,2,1])

(1*4 + 2*3 + 3*2 + 4*1)/(4+3+2+1)

In [ ]:
# average(array, weight=weight)

np.average(array,weights=weight)

2.0

In [ ]:
NumPy & SciPy

In [ ]:
array = np.array([-10,0.3,1.5,19,-50, -3.5, 11.5, 9])

In [ ]:
array

array([-10. ,   0.3,   1.5,  19. , -50. ,  -3.5,  11.5,   9. ])

In [ ]:
np.sort(array)

array([-50. , -10. ,  -3.5,   0.3,   1.5,   9. ,  11.5,  19. ])

* argsort()

In [ ]:
np.argsort(array)

array([4, 0, 5, 1, 2, 7, 6, 3])

# New section

In [ ]:
array ** 2

array([1.0000e+02, 9.0000e-02, 2.2500e+00, 3.6100e+02, 2.5000e+03,
       1.2250e+01, 1.3225e+02, 8.1000e+01])

In [ ]:
# sqrt()

np.sqrt(newarr)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [ ]:
newarr

array([ 2,  4,  6,  8, 10])

In [ ]:
np.square(newarr)

array([  4,  16,  36,  64, 100])

In [ ]:
"Hello world'

SyntaxError: ignored